apiVersion: apps/v1
kind: Deployment
metadata:
  name: newspaper-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newspaper-backend
  template:
    metadata:
      labels:
        app: newspaper-backend
    spec:
      containers:
        - name: backend
          image: kct_srs_newspaperproject-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: newspaper-config
                  key: MONGO_URI
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: newspaper-secret
                  key: SESSION_SECRET
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
